### ISSUE TITLE
Buffer too small error with I2C read

### ISSUE THREAD

**Issue by petewarden** [usefulsensors/person_sensor_circuit_python#1]
*submitted by a user*

I've been trying to run the [code.py](https://github.com/usefulsensors/person_sensor_circuit_python/blob/ee55af8857b62729b62f61b461d0a7df33412cc9/code.py) file on both an Adafruit Feather STM32 and UM FeatherS2, always getting the same result:

RuntimeError: buffer too small on [this line](https://github.com/usefulsensors/person_sensor_circuit_python/blob/ee55af8857b62729b62f61b461d0a7df33412cc9/code.py#L84).

I tried simplifying the code by eliminating all "display" references, but I keep getting the same error on the same line. These MCUs are pretty powerful and I doubt it is a memory issue. I also tried with two different versions of CircuitPython: 7 and 8. 

I couldn't find anything related to this issue in the Developer Guide. Have you or your team encountered this issue in the past?.

**Comment by Moving-Electrons** [comment]
Update:

This seems to be related to a faulty Person Sensor. I got my hands on another one and the script runs without any issues. Hopefully this is not a widespread thing.

**Comment by petewarden** [comment]
Thanks @Moving-Electrons ! Linking to https://github.com/dupontgu/person-sensor-circuitpython/issues/1 and closing for now.
